#!/bin/sh -eu
# Ma_Sys.ma Script to Decode GiroCode PDFs 1.0.0, Copyright (c) 2022 Ma_Sys.ma.
# For further info send an e-mail to Ma_Sys.ma@web.de.

# requires zbar-tools

tmp="/tmp/decode$$.png"
convert -density 600 "$1" "$tmp"
zbarimg -S*.enable=0 -Sqrcode.enable=1 "$tmp" | \
					"$(dirname "$0")/decode_girocode"
rm "$tmp"
